#ifndef CDROID_CONFIG_H
#define CDROID_CONFIG_H

#define CDROID_PASSWORD "12345"
#define CDOIRD_MOTOR_FRONTRIGHT 3
#define CDOIRD_MOTOR_FRONTLEFT 4
#define CDOIRD_MOTOR_BACKLEFT 1
#define CDOIRD_MOTOR_BACKRIGHT 2
#define CDROID_MOTOR_AUTO_STOP_TIME 1000

#endif

