#ifndef NET_MSG_H
#define NET_MSG_H

#define NETMSG_LOGIN 1
#define NETMSG_AUTH_OK 2
#define NETMSG_AUTH_FAIL 3
#define NETMSG_CDROID_INPUT 4
#define NETMSG_CLIENT_DISCONNECT 5
#define NETMSG_CDROID_DISCONNECT 6
#define NETMSG_CAPTURE_SHOT 7
#define NETMSG_SHOT_BEGIN 8
#define NETMSG_SHOT_PIECE 9
#define NETMSG_SHOT_END 10

#endif
